language: node_js
node_js:
- '6.1'
env:
  global:
  - GH_REF: github.com/chad-autry/wac-bp
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm run clean
- npm run build
after_success:
- chmod ugo+x ./push-units.sh
- ./push-units.sh
